# Generated by Django 3.0.2 on 2020-05-24 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('first_name', models.CharField(max_length=20, verbose_name='first_name')),
                ('last_name', models.CharField(blank=True, max_length=20, verbose_name='last_name')),
                ('gender', models.NullBooleanField(choices=[(True, '女'), (False, '男')], default=False, verbose_name='性别')),
                ('birth', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('country', models.CharField(blank=True, max_length=20, verbose_name='国家/地区')),
            ],
            options={
                'verbose_name': '作者',
                'verbose_name_plural': '作者',
                'db_table': 'author',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('title', models.CharField(max_length=200, verbose_name='书名')),
                ('title_cn', models.CharField(blank=True, max_length=100, verbose_name='中文书名')),
                ('author_name_str', models.CharField(blank=True, max_length=2000, verbose_name='作者名')),
                ('author_name_str_cn', models.CharField(blank=True, max_length=2000, verbose_name='作者名')),
                ('subtitle', models.CharField(blank=True, max_length=200, verbose_name='副标题')),
                ('words_hard_level', models.SmallIntegerField(blank=True, choices=[(1, '小学'), (2, '初中'), (3, '高中'), (4, '四级'), (5, '考研'), (6, '六级'), (7, '专四'), (8, '专八')], default=4, null=True, verbose_name='词级难度')),
                ('frequnce_hard_score', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='词频难度')),
                ('words_nums', models.IntegerField(blank=True, null=True, verbose_name='单词数')),
                ('aword_nums', models.IntegerField(blank=True, null=True, verbose_name='不同词数')),
                ('guten_id', models.IntegerField(blank=True, null=True, verbose_name='引用id')),
                ('guten_down_nums', models.IntegerField(blank=True, null=True, verbose_name='下载次数')),
                ('publisher_name', models.CharField(blank=True, max_length=100, verbose_name='出版社名')),
                ('publisher_co_name', models.CharField(blank=True, max_length=100, verbose_name='出品方')),
                ('translator_name', models.CharField(blank=True, max_length=100, verbose_name='译者名')),
                ('time_str', models.CharField(blank=True, max_length=20, verbose_name='出版时间字符')),
                ('time', models.DateField(blank=True, null=True, verbose_name='出版时间')),
                ('page_num_str', models.CharField(blank=True, max_length=20, verbose_name='页数字符')),
                ('page_num', models.SmallIntegerField(blank=True, null=True, verbose_name='页数')),
                ('price_str', models.CharField(blank=True, max_length=20, verbose_name='定价字符')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='定价')),
                ('binding', models.CharField(blank=True, max_length=50, verbose_name='装帧')),
                ('isbn', models.CharField(blank=True, max_length=15, verbose_name='ISBN')),
                ('douban_score', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='豆瓣评分')),
                ('douban_score_num', models.IntegerField(blank=True, null=True, verbose_name='人数')),
                ('content_intro', models.TextField(blank=True, max_length=10000, verbose_name='内容简介')),
                ('author_intro', models.TextField(blank=True, max_length=10000, verbose_name='作者简介')),
                ('douban_subject_id', models.CharField(blank=True, max_length=15, verbose_name='豆瓣ID')),
                ('douban_pid_id', models.CharField(blank=True, max_length=15, verbose_name='豆瓣图片ID')),
                ('douban_series_id', models.CharField(blank=True, max_length=10, verbose_name='丛书id')),
                ('info_comp', models.NullBooleanField(default=False, verbose_name='信息完整')),
            ],
            options={
                'verbose_name': '图书',
                'verbose_name_plural': '图书',
                'db_table': 'book',
            },
        ),
        migrations.CreateModel(
            name='BookAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('translator', models.BooleanField(default=False, verbose_name='译者')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Author')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Book')),
            ],
            options={
                'verbose_name': '图书作者',
                'verbose_name_plural': '图书作者',
                'db_table': 'bookauthor',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(blank=True, through='book.BookAuthor', to='book.Author', verbose_name='作者'),
        ),
    ]
